#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=14gb,walltime=00:30:00
#PBS -N app-cut-tractmeasures-nodes
#PBS -V

singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./cut-nodes.py

if [[ ! -f ./output/tractmeasures.csv ]]; then
	echo "something went wrong"
	exit 1
else
	echo 'complete'
	exit 0
fi
